### ISSUE TITLE
Unable to build locally with apple silicon (macOS 12.0)

### ISSUE THREAD

**Issue by unphased** [finestructure/Hummingbird#39]
<img width="1600" alt="Screen Shot 2021-10-29 at 2 31 32 AM" src="https://user-images.githubusercontent.com/1542910/139386930-dbc356c7-0772-4f1c-baf3-a1163c092873.png">

I have made no changes other than to change the deployment target from I believe it was 10.12 to 12.0. I have attempted to build with `develop` and on `3.1.7` tag. Do you know what might cause the compilation errors? Unfortunately I do not know any Swift. 

Thanks

**Comment by unphased** [comment]
I will for the time being use the key based window drag feature built into BetterTouchTool, there is no way I can live without that app anyway. But Hummingbird will always be in my heart. 💕

**Comment by finestructure** [comment]
Thanks for the report, @unphased ! I haven't built Hummingbird lately but the downloadable version is from this repository: https://hbird.app, if you want to give that a try.

**Comment by finestructure** [comment]
And it is universal Intel/ARM, of course.

**Comment by finestructure** [comment]
Fixed by #40
